services:
  - type: web
    name: uzima-api
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run start:api
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 8787
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: uzima-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ALLOW_DEMO_OTP
        value: "false"
      - key: ENABLE_SIMULATED_WALLET
        value: "false"
      - key: ALLOW_BODY_REFRESH
        value: "false"
      - key: EMAIL_PROVIDER
        sync: false
      - key: AFYAX_WEBHOOK_SECRET
        generateValue: true
      - key: STORAGE_LOCAL_PATH
        value: ./storage
      - key: CORS_ORIGINS
        value: https://uzima-portal.onrender.com
      - key: REDIS_URL
        sync: false
      - key: COOKIE_SECURE
        value: "true"
  - type: web
    name: uzima-portal
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: VITE_API_URL
        value: https://uzima-api.onrender.com

databases:
  - name: uzima-db
    plan: starter
